//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapStone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pharmacy
    {
        public int PharmacyDataId { get; set; }
        public string MemberFirstName { get; set; }
        public string MemberLastName { get; set; }
        public string MemberMiddleInitial { get; set; }
        public Nullable<double> DateofBirth { get; set; }
        public string Gender { get; set; }
        public Nullable<double> FillDate { get; set; }
        public string ClaimStatus { get; set; }
        public string ClaimNumber { get; set; }
        public string OriginalClaimNumber { get; set; }
        public Nullable<double> PerscriptionNumber { get; set; }
        public Nullable<double> NDCCode { get; set; }
        public string DrugName { get; set; }
        public string OTCIndicator { get; set; }
        public Nullable<double> Multisource { get; set; }
        public Nullable<double> DEASchedule { get; set; }
        public string DiagnosisCode { get; set; }
        public Nullable<double> DWAIndecator { get; set; }
        public Nullable<double> DaysSupply { get; set; }
        public Nullable<double> BilledAmount { get; set; }
        public string PharmacyProviderID { get; set; }
        public Nullable<double> PrescribingProviderID { get; set; }
        public Nullable<double> RefillCode { get; set; }
        public Nullable<double> blankSpace { get; set; }
        public string NCPDPrejectcodes { get; set; }
        public Nullable<double> NPI { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip_Code { get; set; }
        public Nullable<double> MemberId { get; set; }
    }
}
